import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"


export const metadata: Metadata = {
  title: "Rakshak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
